"""empty message

Revision ID: 6682682e9e05
Revises: 097388a67e32
Create Date: 2025-05-13 17:23:44.596048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6682682e9e05'
down_revision: Union[str, None] = '097388a67e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondname', sa.String(), nullable=True))
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'secondname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
