"""empty message

Revision ID: f58c7c437658
Revises: e0dd1d4532f8
Create Date: 2025-04-25 01:59:32.904272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58c7c437658'
down_revision: Union[str, None] = 'e0dd1d4532f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'updated_on')
    # ### end Alembic commands ###
